import React, { useState, useMemo } from 'react';
import { Calendar as CalendarIcon, Clock, CheckCircle2, Circle, Microscope, Activity, Plus, Trash2, X } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import './Scheduler.css';

export default function Scheduler({ state, updateState, can }) {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [showEventModal, setShowEventModal] = useState(false);
  const [newEventForm, setNewEventForm] = useState({ title: '', recurrencePattern: 'none' });
  
  // State slices
  const cages = state?.cages || [];
  const cultures = state?.cultures || [];
  const manualEvents = state?.calendarEvents || [];

  // 1. Auto-generate events from Cages
  const generatedEvents = useMemo(() => {
    let events = [];
    
    // Generar eventos automáticos de Jaulas
    cages.forEach(cage => {
      if (!cage.startDate || cage.recurrencePattern === 'none' || !cage.recurrencePattern) return;
      
      const start = new Date(cage.startDate);
      start.setHours(0,0,0,0);
      
      // Proyectar 30 días hacia atrás y 60 días hacia adelante desde hoy
      const today = new Date();
      const lookback = new Date(today);
      lookback.setDate(lookback.getDate() - 30);
      
      const lookahead = new Date(today);
      lookahead.setDate(lookahead.getDate() + 60);

      let current = new Date(start);
      if (current < lookback) current = new Date(lookback);

      while (current <= lookahead) {
        // Verificar regla de recurrencia
        let shouldAdd = false;
        
        if (cage.recurrencePattern === 'daily') shouldAdd = true;
        if (cage.recurrencePattern === 'every_2_days') {
          const diff = Math.floor((current - start) / (1000*60*60*24));
          if (diff % 2 === 0) shouldAdd = true;
        }
        if (cage.recurrencePattern === 'every_3_days') {
          const diff = Math.floor((current - start) / (1000*60*60*24));
          if (diff % 3 === 0) shouldAdd = true;
        }
        if (cage.recurrencePattern === 'weekly') {
          if (current.getDay() === start.getDay()) shouldAdd = true;
        }

        if (shouldAdd) {
          events.push({
            id: `auto-cage-${cage.id}-${current.toISOString().split('T')[0]}`,
            date: current.toISOString().split('T')[0],
            title: `Check/Dosis: ${cage.name}`,
            type: 'cage',
            referenceId: cage.id,
            autoGenerated: true,
            status: 'pending' // En el futuro se puede mapear si se completó hoy
          });
        }
        
        current.setDate(current.getDate() + 1);
      }
    });



    // Proyectar eventos manuales
    manualEvents.forEach(ev => {
      if (!ev.isRecurring) {
        events.push(ev);
        return;
      }
      
      const start = new Date(ev.startDate);
      start.setHours(0,0,0,0);
      
      const today = new Date();
      const lookback = new Date(today);
      lookback.setDate(lookback.getDate() - 30);
      
      const lookahead = new Date(today);
      lookahead.setDate(lookahead.getDate() + 60);

      let current = new Date(start);
      if (current < lookback) current = new Date(lookback);

      while (current <= lookahead) {
        let shouldAdd = false;
        
        if (ev.recurrencePattern === 'daily') shouldAdd = true;
        if (ev.recurrencePattern === 'weekdays') {
          const dayOfWeek = current.getDay();
          if (dayOfWeek >= 1 && dayOfWeek <= 5) shouldAdd = true; // Lun-Vie
        }
        if (ev.recurrencePattern === 'every_3_days') {
          const diff = Math.floor((current - start) / (1000*60*60*24));
          if (diff % 3 === 0) shouldAdd = true;
        }
        if (ev.recurrencePattern === 'weekly') {
          if (current.getDay() === start.getDay()) shouldAdd = true;
        }

        if (shouldAdd) {
          const dStr = current.toISOString().split('T')[0];
          events.push({
            id: `recurring-${ev.id}-${dStr}`,
            parentId: ev.id,
            date: dStr,
            title: ev.title,
            type: ev.type,
            autoGenerated: false,
            isRecurringInstance: true,
            status: (ev.completedDates && ev.completedDates.includes(dStr)) ? 'done' : 'pending'
          });
        }
        
        current.setDate(current.getDate() + 1);
      }
    });

    return events;
  }, [cages, manualEvents]);

  // Funciones de Calendario
  const getDaysInMonth = (year, month) => new Date(year, month + 1, 0).getDate();
  const getFirstDayOfMonth = (year, month) => new Date(year, month, 1).getDay();

  const prevMonth = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
  const nextMonth = () => setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));

  const renderCalendarDays = () => {
    const year = currentDate.getFullYear();
    const month = currentDate.getMonth();
    const daysInMonth = getDaysInMonth(year, month);
    const firstDay = getFirstDayOfMonth(year, month);
    
    const days = [];
    // Espacios vacíos al principio
    for (let i = 0; i < firstDay; i++) {
      days.push(<div key={`empty-${i}`} className="calendar-day empty"></div>);
    }
    
    // Días reales
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      const dayEvents = generatedEvents.filter(e => e.date === dateStr);
      const isSelected = selectedDate === dateStr;
      
      const isToday = dateStr === new Date().toISOString().split('T')[0];

      days.push(
        <div 
          key={day} 
          className={`calendar-day ${isSelected ? 'selected' : ''} ${isToday ? 'today' : ''}`}
          onClick={() => setSelectedDate(dateStr)}
        >
          <div className="day-number">{day}</div>
          <div className="day-events-dots">
            {dayEvents.slice(0, 3).map((e, i) => (
              <span key={i} className={`event-dot ${e.type}`}></span>
            ))}
            {dayEvents.length > 3 && <span className="event-dot-more">+{dayEvents.length - 3}</span>}
          </div>
        </div>
      );
    }
    return days;
  };

  const selectedDayEvents = generatedEvents.filter(e => e.date === selectedDate).sort((a, b) => {
    if (a.status === 'done' && b.status !== 'done') return 1;
    if (a.status !== 'done' && b.status === 'done') return -1;
    return 0;
  });

  const openEventModal = () => {
    setNewEventForm({ title: '', recurrencePattern: 'none' });
    setShowEventModal(true);
  };

  const saveManualEvent = () => {
    if (!newEventForm.title.trim()) return;
    const isRecurring = newEventForm.recurrencePattern !== 'none';
    const newEvent = {
      id: uuidv4(),
      title: newEventForm.title,
      date: isRecurring ? undefined : selectedDate, // Use startDate for recurring
      startDate: isRecurring ? selectedDate : undefined,
      type: 'general',
      status: 'pending',
      isRecurring,
      recurrencePattern: newEventForm.recurrencePattern,
      completedDates: isRecurring ? [] : undefined
    };
    updateState({ calendarEvents: [...manualEvents, newEvent] });
    setShowEventModal(false);
  };

  const toggleEventStatus = (ev, isAuto) => {
    if (isAuto) {
      alert("Los eventos auto-generados de jaulas se rigen por la regla de la jaula. Ve a Jaulas para cambiar su configuración.");
      return;
    }
    
    if (ev.isRecurringInstance) {
      const updated = manualEvents.map(mEv => {
        if (mEv.id === ev.parentId) {
          const doneList = mEv.completedDates || [];
          const isDone = doneList.includes(ev.date);
          return {
            ...mEv,
            completedDates: isDone 
              ? doneList.filter(d => d !== ev.date) 
              : [...doneList, ev.date]
          };
        }
        return mEv;
      });
      updateState({ calendarEvents: updated });
    } else {
      const updated = manualEvents.map(mEv => 
        mEv.id === ev.id ? { ...mEv, status: mEv.status === 'done' ? 'pending' : 'done' } : mEv
      );
      updateState({ calendarEvents: updated });
    }
  };

  const deleteEvent = (ev, isAuto) => {
    if (isAuto) return;
    const targetId = ev.isRecurringInstance ? ev.parentId : ev.id;
    const msg = ev.isRecurringInstance ? '¿Eliminar toda la serie de este evento recurrente?' : '¿Eliminar evento?';
    if (confirm(msg)) {
      updateState({ calendarEvents: manualEvents.filter(mEv => mEv.id !== targetId) });
    }
  };

  const getIconForType = (type) => {
    if (type === 'cage') return <Activity size={16} color="#ef4444" />;
    if (type === 'culture') return <Microscope size={16} color="#10b981" />;
    return <Clock size={16} color="#3b82f6" />;
  };

  return (
    <div className="scheduler-container">
      <div className="scheduler-header glass-panel">
        <h2 style={{color: 'var(--text-primary)', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '8px'}}>
          <CalendarIcon size={24} color="var(--accent)"/> Cronograma Automatizado
        </h2>
        <p className="no-print" style={{color: 'var(--text-secondary)', fontSize: '0.9rem'}}>Planea mantenimientos de cultivos y tratamientos en animales.</p>
      </div>

      <div className="scheduler-grid">
        {/* Calendario Mensual */}
        <div className="glass-panel calendar-panel">
          <div className="calendar-controls">
            <button className="btn" onClick={prevMonth}>&lt;</button>
            <h3 style={{ margin: 0, color: 'var(--text-primary)' }}>
              {currentDate.toLocaleString('es', { month: 'long', year: 'numeric' }).toUpperCase()}
            </h3>
            <button className="btn" onClick={nextMonth}>&gt;</button>
          </div>
          
          <div className="calendar-weekdays">
            <span>Dom</span><span>Lun</span><span>Mar</span><span>Mié</span><span>Jue</span><span>Vie</span><span>Sáb</span>
          </div>
          
          <div className="calendar-days-grid">
            {renderCalendarDays()}
          </div>
        </div>

        {/* Agenda del Día Seleccionado */}
        <div className="glass-panel agenda-panel">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', borderBottom: '1px solid var(--panel-border)', paddingBottom: '12px' }}>
            <h3 style={{ margin: 0, color: 'var(--text-primary)' }}>
              Agenda: {new Date(selectedDate + 'T12:00:00').toLocaleDateString('es', { weekday: 'long', day: 'numeric', month: 'short' })}
            </h3>
            <button className="btn-icon no-print" onClick={openEventModal} style={{ background: 'var(--accent)', color: 'white' }}>
              <Plus size={16}/>
            </button>
          </div>

          <div className="agenda-list">
            {selectedDayEvents.length === 0 ? (
              <div style={{ textAlign: 'center', color: 'var(--text-secondary)', marginTop: '40px' }}>
                <CheckCircle2 size={40} style={{ opacity: 0.2, marginBottom: '12px' }} />
                <p>No hay eventos programados para este día.</p>
              </div>
            ) : (
              selectedDayEvents.map(ev => (
                <div key={ev.id} className={`agenda-item ${ev.status === 'done' ? 'done' : ''} ${ev.type}`}>
                  <div className="agenda-item-left" onClick={() => toggleEventStatus(ev, ev.autoGenerated)}>
                    {ev.status === 'done' ? <CheckCircle2 size={20} color="var(--success)" /> : <Circle size={20} color="var(--text-secondary)" />}
                  </div>
                  <div className="agenda-item-content">
                    <div className="agenda-item-title">{ev.title}</div>
                    <div className="agenda-item-meta">
                      {getIconForType(ev.type)} 
                      {ev.autoGenerated ? 'Auto-generado' : (ev.isRecurringInstance ? 'Recurrente' : 'Manual')}
                    </div>
                  </div>
                  {!ev.autoGenerated && (
                    <button className="btn-icon no-print delete-btn" onClick={() => deleteEvent(ev, ev.autoGenerated)}>
                      <Trash2 size={14} />
                    </button>
                  )}
                </div>
              ))
            )}
          </div>
          
          <button className="btn btn-primary no-print" style={{ width: '100%', marginTop: '20px' }} onClick={() => window.print()}>
            Imprimir Agenda del Día
          </button>
        </div>
      </div>

      {showEventModal && (
        <div className="modal-overlay">
          <div className="modal-content glass-panel" style={{width: '400px'}}>
            <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px'}}>
              <h3 style={{margin: 0}}>Añadir Evento ({selectedDate})</h3>
              <button className="btn-icon" onClick={() => setShowEventModal(false)}><X size={20}/></button>
            </div>
            
            <div style={{marginBottom: '16px'}}>
              <label className="input-label">Título del Evento / Tarea</label>
              <input 
                className="input-field" 
                style={{width: '100%'}} 
                placeholder="Ej. Limpieza general, Cambio de filtros..."
                value={newEventForm.title}
                onChange={e => setNewEventForm({...newEventForm, title: e.target.value})}
                autoFocus
              />
            </div>
            
            <div style={{marginBottom: '24px'}}>
              <label className="input-label">Patrón de Recurrencia</label>
              <select 
                className="input-field" 
                style={{width: '100%'}}
                value={newEventForm.recurrencePattern}
                onChange={e => setNewEventForm({...newEventForm, recurrencePattern: e.target.value})}
              >
                <option value="none">Una sola vez</option>
                <option value="daily">Diario</option>
                <option value="weekdays">Lunes a Viernes</option>
                <option value="every_3_days">Cada 3 días</option>
                <option value="weekly">Semanal (Mismo día)</option>
              </select>
            </div>

            <div style={{display: 'flex', gap: '10px', justifyContent: 'flex-end'}}>
              <button className="btn" onClick={() => setShowEventModal(false)}>Cancelar</button>
              <button className="btn btn-primary" onClick={saveManualEvent}>Guardar Evento</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
